// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServiceClient interface {
	SayHello(ctx context.Context, in *Void, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetService_SayHelloStreamingClient, error)
	SayHelloClientStream(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHelloClientStreamClient, error)
	SayHelloBinddirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHelloBinddirectionalStreamingClient, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) SayHello(ctx context.Context, in *Void, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greet_service.GreetService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) SayHelloStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetService_SayHelloStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greet_service.GreetService/SayHelloStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHelloStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_SayHelloStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSayHelloStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHelloStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SayHelloClientStream(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHelloClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greet_service.GreetService/SayHelloClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHelloClientStreamClient{stream}
	return x, nil
}

type GreetService_SayHelloClientStreamClient interface {
	Send(*HelloResponse) error
	CloseAndRecv() (*MessagesList, error)
	grpc.ClientStream
}

type greetServiceSayHelloClientStreamClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHelloClientStreamClient) Send(m *HelloResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSayHelloClientStreamClient) CloseAndRecv() (*MessagesList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessagesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SayHelloBinddirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHelloBinddirectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/greet_service.GreetService/SayHelloBinddirectionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHelloBinddirectionalStreamingClient{stream}
	return x, nil
}

type GreetService_SayHelloBinddirectionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSayHelloBinddirectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHelloBinddirectionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSayHelloBinddirectionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
// All implementations must embed UnimplementedGreetServiceServer
// for forward compatibility
type GreetServiceServer interface {
	SayHello(context.Context, *Void) (*HelloResponse, error)
	SayHelloStreaming(*NamesList, GreetService_SayHelloStreamingServer) error
	SayHelloClientStream(GreetService_SayHelloClientStreamServer) error
	SayHelloBinddirectionalStreaming(GreetService_SayHelloBinddirectionalStreamingServer) error
	mustEmbedUnimplementedGreetServiceServer()
}

// UnimplementedGreetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (UnimplementedGreetServiceServer) SayHello(context.Context, *Void) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServiceServer) SayHelloStreaming(*NamesList, GreetService_SayHelloStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStreaming not implemented")
}
func (UnimplementedGreetServiceServer) SayHelloClientStream(GreetService_SayHelloClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloClientStream not implemented")
}
func (UnimplementedGreetServiceServer) SayHelloBinddirectionalStreaming(GreetService_SayHelloBinddirectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloBinddirectionalStreaming not implemented")
}
func (UnimplementedGreetServiceServer) mustEmbedUnimplementedGreetServiceServer() {}

// UnsafeGreetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiceServer will
// result in compilation errors.
type UnsafeGreetServiceServer interface {
	mustEmbedUnimplementedGreetServiceServer()
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet_service.GreetService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SayHello(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_SayHelloStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamesList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).SayHelloStreaming(m, &greetServiceSayHelloStreamingServer{stream})
}

type GreetService_SayHelloStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetServiceSayHelloStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHelloStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_SayHelloClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SayHelloClientStream(&greetServiceSayHelloClientStreamServer{stream})
}

type GreetService_SayHelloClientStreamServer interface {
	SendAndClose(*MessagesList) error
	Recv() (*HelloResponse, error)
	grpc.ServerStream
}

type greetServiceSayHelloClientStreamServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHelloClientStreamServer) SendAndClose(m *MessagesList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSayHelloClientStreamServer) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_SayHelloBinddirectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SayHelloBinddirectionalStreaming(&greetServiceSayHelloBinddirectionalStreamingServer{stream})
}

type GreetService_SayHelloBinddirectionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSayHelloBinddirectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHelloBinddirectionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSayHelloBinddirectionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloStreaming",
			Handler:       _GreetService_SayHelloStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloClientStream",
			Handler:       _GreetService_SayHelloClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloBinddirectionalStreaming",
			Handler:       _GreetService_SayHelloBinddirectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
